### ISSUE TITLE
Implement a basic voting mechanism.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/edge-governance#4]
We need to actually build the voting mechanism.

Some ideas:
* Allow an API call to manually change voting state, for testing purposes.

**Comment by drewstone** [comment]
The voting mechanism can largely be taken from existing modules for time savings. Here is an example from Council which is simple (requires new storage and obviously tallying procedure at the end of proposal duration)
```
		fn vote(origin, proposal: T::Hash, approve: bool) {
			let who = ensure_signed(origin)?;

			ensure!(Self::is_councillor(&who), "only councillors may vote on council proposals");

			if Self::vote_of((proposal, who.clone())).is_none() {
				<ProposalVoters<T>>::mutate(proposal, |voters| voters.push(who.clone()));
			}
			<CouncilVoteOf<T>>::insert((proposal, who), approve);
		}
```
